debug: true

sentry:
  user: "d0d0d3f94c4e449cbfaa4fa913b05e9a"
  password: "e184044f08db44ccbe19798e5c764286"
  url: "app.getsentry.com/35003"

mongo:
  ip: "104.196.60.133"
  port: "27017"
  database: "qalorie-staging"

app:
  baseUrl: "http://staging.qalorie.com"
  domain: "staging.qalorie.com"
  host: "localhost"
  port: 3000

auth:
  auth_token_secret: 'adfbb423-a9af-4494-9ee0-418c70734fa4'

facebook:
  client_id: '1577823505867388'
  client_secret: 'c619acd8c6712a0015aa172d04fb857b'
  callback_url: 'http://staging.qalorie.com/auth/facebook/callback'

sendgrid:
  app_id: 'qalorie-app'
  secret_id: 'tzP6RKFDFXmADRJC'
  recover_id: '36640625-93bc-4628-a8ef-2c596addd583'
  welcome_id: '8b0a29a7-a353-4ffd-af22-36096d359429'  
  delete_id:  'b2d0455b-305f-4986-a16f-7a0d72c496f5'
  support_id:  '9cbbff61-d340-4a9b-b561-55bd547d7837'
  ft_upgrade_id:  '3626efa0-9f33-4574-b561-e43cec5336bc'
  accept_nutritionist_id:  '57d63308-4f3e-44bc-9154-7b631d0ca8df'
  decline_nutritionist_id:  'd6745187-3742-4e1d-8313-f15557d7904c'
  suspend_nutritionist_id:  '090eb3ea-ca18-4fe1-8cde-ee5a6cf0aeeb'
  activate_nutritionist_id:  'd3e28634-0be6-4129-bc3d-b2b440194b9c'
  remove_nutritionist_id:  '62e50f1f-e2c8-488d-943a-d50f143b4c29'

stripe:
  private_key: 'sk_test_9sIM8w8x4WrClNvIo0QgzK4U'
  public_key: 'pk_test_ztzb4BStDrCTXAJbCCSvtMLJ'

  plans:
    trial:
      id: '031T'
      amount: 2995
      name: 'Free Trial'

    monthly:
      id: '031'
      amount: 2995
      name: 'Monthly'

    yearly:
      id: '0365'
      amount: 29950
      name: 'Yearly'

  products:
    appointments:
      id: '1_app'
      discount:
        4: 0
        6: 2995
        1: 0
        2: 0
        12: 8985


emails:
  sender_name: 'Qalorie'
  sender: 'service@qalorie.com'
  support: 'ticket@qalorie.com'
